import { useUser } from '@auth0/nextjs-auth0';
import { useState } from "react";
import Image from "next/image";
import Head from "next/head";
import Link from 'next/link';

interface Props {
  children: React.ReactNode
}

const MainLayout: React.FC<Props> = ({ children }) => {
  const { user, isLoading, error} = useUser();

  const [theme, setTheme] = useState("dark");

  // const onThemeChange = () => {
  //   setTheme("bumblebee");
  // };

  return (
    <div data-theme={theme} className="">
      <Head>
        <title>Planetary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="navbar bg-base-300 shadow-xl">
        <div className="flex-1 gap-2">
          <Image
            src="./planetlogo.svg"
            className="ml-3 mr-3 h-6 sm:h-9 fill-white"
            alt="Planetary Logo"
            width={32}
            height={32}
          />
          <span className="self-center whitespace-nowrap text-2xl font-semibold text-white">
            Planetary
          </span>
        </div>
        <div className="flex-none">
          <ul className="menu menu-horizontal p-0">
            {!user && (
              <li>
                <Link href="/api/auth/login">Log in</Link >
              </li>
            )}
            {user && (
              <>
                <li>
                <Link href="/api/auth/logout">
                    Log out
                  </Link >
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
      <div className="p-2">{children}</div>
    </div>
  );
};

export default MainLayout;
