import { useAuth0 } from "@auth0/auth0-react";
import { useState } from "react";
import Image from "next/image";
import Head from "next/head";

interface Props {
  children: any;
}

const MainLayout: React.FC<Props> = ({ children }) => {
  const { isAuthenticated, isLoading, loginWithRedirect, logout } =
    useAuth0();

  const [theme, setTheme] = useState("dark");

  if (isLoading) {
    return <div>Loading ...</div>;
  }
  // const onThemeChange = () => {
  //   setTheme("bumblebee");
  // };

  return (
    <div data-theme={theme} className="">
      <Head>
        <title>Planetary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="navbar bg-base-300 shadow-xl">
        <div className="flex-1 gap-2">
          <Image
            src="./planetlogo.svg"
            className="ml-3 mr-3 h-6 sm:h-9 fill-white"
            alt="Planetary Logo"
            width={32}
            height={32}
          />
          <span className="self-center whitespace-nowrap text-2xl font-semibold text-white">
            Planetary
          </span>
        </div>
        <div className="flex-none">
          <ul className="menu menu-horizontal p-0">
            {!isAuthenticated && (
              <li>
                <a onClick={loginWithRedirect}>Sign in</a>
              </li>
            )}
            {isAuthenticated && (
              <>
                <li>
                  <a
                    onClick={() => logout({ returnTo: window.location.origin })}
                  >
                    Log out
                  </a>
                </li>
              </>
            )}
          </ul>
        </div>
      </div>
      <div className="p-2">{children}</div>
    </div>
  );
};

export default MainLayout;
